import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import Traveles from '../components/Traveles';
import Team from '../components/Team';
import Info from '../components/Info';
import LoginForm from '../components/LoginForm';
import Actions from '../components/Actions';
import PicturesSlider from '../components/Slider';
import styles from '../styles/Home.module.scss';
import Footer from '../components/Footer';

export default function Home() {
  return (
    // <div className={styles.container}>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Traveles />
      <Team />
      <Info />
      <LoginForm />
      <Actions />
      <PicturesSlider />
      <Footer />

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
